### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Tupiao** [heanhan/OpenCore-0.94-DELL--7080MFF-EFI#2]
大佬我使用了你的这套EFI引导安装为什么一直重启？

**Comment by heanhan** [comment]
把电脑配置发出来看看，和我的配置一样吗？

**Comment by heanhan** [comment]
> 大佬我使用了你的这套EFI引导安装为什么一直重启？
bios设置和我一样吗？电脑配置和我一样吗？你可以把你的配置发出来今天重新上传了一版本，解决偶尔无故重启的问题，目前是已经使用一周没有发生重启，趋于稳定，目前当成主力开发机在写代码。

**Comment by Tupiao** [comment]
主机是7080mff&nbsp; bios版本是最新的版本 cpu i5 10400 bios设置跟你上面设置的一样。 在进入第二阶段的时候&nbsp; 出现苹果logo就重启&nbsp; 第一阶段安装的时候显示大概还剩12分钟的时候直接重启 这个问题时没有正确安装吗？
&nbsp;


强强嘛&nbsp;i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月29日(星期二) 下午3:05
收件人: ***@***.***&gt;; 
抄送: "强强嘛 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [heanhan/OpenCore-0.94-DELL--7080MFF-EFI] 安装问题 (Issue #2)





  
大佬我使用了你的这套EFI引导安装为什么一直重启？
 bios设置和我一样吗？电脑配置和我一样吗？你可以把你的配置发出来今天重新上传了一版本，解决偶尔无故重启的问题，目前是已经使用一周没有发生重启，趋于稳定，目前当成主力开发机在写代码。

**Comment by Tupiao** [comment]
我之前用的是另一台主机 直接把硬盘查下来了  然后直接把你的上一个版本的EFI放进引导中 正常使用。然后我准备重新安装一下  用你的上一个版本的（纯文字引导版本的那个没有 安装系统的选项）。新版本引导（前几天上传的）安装就会出现上述我说的情况

**Comment by Tupiao** [comment]
> > 大佬我使用了你的这套EFI引导安装为什么一直重启？
> > bios设置和我一样吗？电脑配置和我一样吗？你可以把你的配置发出来今天重新上传了一版本，解决偶尔无故重启的问题，目前是已经使用一周没有发生重启，趋于稳定，目前当成主力开发机在写代码。

找到问题了 ，是我安装的时候抹掉硬盘的时候格式选择的不对😂
大佬你开机需要多久啊？  我按完开机按钮大概20秒显示dell Logo  1分钟才看到桌面

**Comment by heanhan** [comment]
>

> > > 大佬我使用了你的这套EFI引导安装为什么一直重启？
> > > bios设置和我一样吗？电脑配置和我一样吗？你可以把你的配置发出来今天重新上传了一版本，解决偶尔无故重启的问题，目前是已经使用一周没有发生重启，趋于稳定，目前当成主力开发机在写代码。
> 
> 找到问题了 ，是我安装的时候抹掉硬盘的时候格式选择的不对😂 大佬你开机需要多久啊？ 我按完开机按钮大概20秒显示dell Logo 1分钟才看到桌面

我把opencore的启动界面多余辅助项目全去掉了，按开机按钮，出现logo差不多5秒，然后直接输出苹果logo ，到进入输密码，总时间也就20多秒左右。我是单系统macos, 带的4K显示器。

**Comment by Tupiao** [comment]
> > 
> 
> > > > 大佬我使用了你的这套EFI引导安装为什么一直重启？  bios设置和我一样吗？ 电脑配置和我一样吗？ 你可以把你的配置发出来今天重新上传了一版本，解决偶尔无故重启的问题，目前是已经使用一周没有发生重启，趋于稳定，目前当成主力开发机在写代码。
> > 
> > 
> > 找到问题了 ，是我安装的时候抹掉硬盘的时候格式选择的不对😂 大佬你开机需要多久啊？ 我按完开机按钮大概20秒显示dell Logo 1分钟才看到桌面
> 
> 我把opencore的启动界面多余辅助项目全去掉了，按开机按钮，出现logo差不多5秒，然后直接输出苹果logo ，到进入输密码，总时间也就20多秒左右。 我是单系统macos, 带的4K显示器。

那就是说我这个启动慢应该是主板的问题吗？

**Comment by heanhan** [comment]
> 



> > > 
> > 
> > 
> > > > > 大佬我使用了你的这套EFI引导安装为什么一直重启？  bios设置和我一样吗？ 电脑配置和我一样吗？ 你可以把你的配置发出来今天重新上传了一版本，解决偶尔无故重启的问题，目前是已经使用一周没有发生重启，趋于稳定，目前当成主力开发机在写代码。
> > > 
> > > 
> > > 找到问题了 ，是我安装的时候抹掉硬盘的时候格式选择的不对😂 大佬你开机需要多久啊？ 我按完开机按钮大概20秒显示dell Logo 1分钟才看到桌面
> > 
> > 
> > 我把opencore的启动界面多余辅助项目全去掉了，按开机按钮，出现logo差不多5秒，然后直接输出苹果logo ，到进入输密码，总时间也就20多秒左右。 我是单系统macos, 带的4K显示器。
> 
> 那就是说我这个启动慢应该是主板的问题吗？

你的和我是一个机器，都是Q470, 应该没差别，估计与固态硬盘和内存都有关系，我的固态选的是长江的tiplus5000，在黑苹果下实际测的读写 分别是3200MB/s 左右和2400MB/s。我之前京东上买的内存条不兼容，总是莫名的自动重启，目前内存条，机器稳定了。目前放在公司当主力机器开发。暂时没遇到啥bug。
