### ISSUE TITLE
大佬有试过最新的Sonoma 14吗？

### ISSUE THREAD

**Issue by etscript** [heanhan/OpenCore-0.94-DELL--7080MFF-EFI#3]
大佬有试过最新的Sonoma 14吗？

**Comment by heanhan** [comment]
> 大佬有试过最新的Sonoma 14吗？

不尝试了 ，目前作为写代码的主力机器在使用，升级到了14 也会让我的免去网卡失效，暂时没有好的方案出来之前，暂时停留在13.6 的版本。家里白苹果mbp16寸的升级到了14 ，没啥亮点。
