### ISSUE TITLE
dell OptiPlex 7010能适配下不

### ISSUE THREAD

**Issue by kittyzero520** [heanhan/OpenCore-0.94-DELL--7080MFF-EFI#4]
亲，戴尔的7010台式机，有efi吗？

**Comment by heanhan** [comment]
> 亲，戴尔的7010台式机，有efi吗？

我没有这个机器也不知道你的硬件的信息，github 上有这个 机器的efi搜一下就好，，如果想用最新的oc  使用 OCA tool 工具升级驱动就行了。
