### ISSUE TITLE
Dell OptiPlex 7080 MT可以不可以安装

### ISSUE THREAD

**Issue by zepang** [heanhan/OpenCore-0.94-DELL--7080MFF-EFI#5]
想知道大佬目前使用的是哪个系统的版本，我目前用的13，efi不是你的，现在有个奇怪的问题，启动之后打字和鼠标点击响应都有点卡卡的

**Comment by heanhan** [comment]
> 想知道大佬目前使用的是哪个系统的版本，我目前用的13，efi不是你的，现在有个奇怪的问题，启动之后打字和鼠标点击响应都有点卡卡的

第一 、你的电脑主板Q470 和我的一样 ，你可以尝试用一下试试 ，需要注意你有没有独立显卡，启动中需要配置。第二、我的系统：13.6  基于oc0.95 驱动的  ；第三、卡顿是 也有可能是没有有适配好；先检查你的鼠标和键盘 是有线连接还是蓝牙连接？ 如果是蓝牙连接，你的无线网是连接的2.4G 还是5G 的？ 蓝牙和无线网2.4 的会有冲突，冲突的表面就是触控板鼠标啥的 有延迟。
